name: CI
on: push
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: yarn run eslint . --ext .js,.jsx,.ts,.tsx
